//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *AuthSpec) DeepCopyInto(out *AuthSpec) {
	*out = *in
	out.BasicUserSecret = in.BasicUserSecret
	out.BasicPassHashSecret = in.BasicPassHashSecret
}

// DeepCopy creates a deep copy of AuthSpec.
func (in *AuthSpec) DeepCopy() *AuthSpec {
	if in == nil {
		return nil
	}
	out := new(AuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *LiteMLflow) DeepCopyInto(out *LiteMLflow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of LiteMLflow.
func (in *LiteMLflow) DeepCopy() *LiteMLflow {
	if in == nil {
		return nil
	}
	out := new(LiteMLflow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *LiteMLflow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *LiteMLflowList) DeepCopyInto(out *LiteMLflowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LiteMLflow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of LiteMLflowList.
func (in *LiteMLflowList) DeepCopy() *LiteMLflowList {
	if in == nil {
		return nil
	}
	out := new(LiteMLflowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *LiteMLflowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *LiteMLflowSpec) DeepCopyInto(out *LiteMLflowSpec) {
	*out = *in
	out.Storage = in.Storage
	out.Auth = in.Auth
	out.S3 = in.S3
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy creates a deep copy of LiteMLflowSpec.
func (in *LiteMLflowSpec) DeepCopy() *LiteMLflowSpec {
	if in == nil {
		return nil
	}
	out := new(LiteMLflowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *LiteMLflowStatus) DeepCopyInto(out *LiteMLflowStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of LiteMLflowStatus.
func (in *LiteMLflowStatus) DeepCopy() *LiteMLflowStatus {
	if in == nil {
		return nil
	}
	out := new(LiteMLflowStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *S3Spec) DeepCopyInto(out *S3Spec) {
	*out = *in
	out.AccessKeySecret = in.AccessKeySecret
	out.SecretKeySecret = in.SecretKeySecret
}

// DeepCopy creates a deep copy of S3Spec.
func (in *S3Spec) DeepCopy() *S3Spec {
	if in == nil {
		return nil
	}
	out := new(S3Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy creates a deep copy of SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
}

// DeepCopy creates a deep copy of StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}
