---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: litemlflow-operator
  namespace: litemlflow-system
  labels:
    app.kubernetes.io/name: litemlflow-operator
    app.kubernetes.io/component: controller
