-- v2_baseline.sql — consolidated schema for fresh v2.1+ installs.
--
-- AUTOGENERATED by scripts/gen-baseline-schema. Do not hand-edit.
-- Regenerate: go run ./scripts/gen-baseline-schema > internal/migrations/baseline/v2_baseline.sql
--
-- This file is NOT applied by the runner today; it's the canonical
-- target for the v3.0 migration squash. TestSquashEquivalence in
-- internal/migrations/embed_test.go enforces that applying it produces
-- the same schema as applying 001..NN sequentially.
--
-- v2.1 T4.18 (partial): baseline materialized, runner switch deferred to v3.0.

CREATE TABLE schema_migrations (
			version    INTEGER PRIMARY KEY,
			name       TEXT NOT NULL,
			applied_at INTEGER NOT NULL
		);

CREATE TABLE experiment_tags (
    experiment_id INTEGER NOT NULL,
    key           TEXT    NOT NULL,
    value         TEXT    NOT NULL,
    PRIMARY KEY (experiment_id, key),
    FOREIGN KEY (experiment_id) REFERENCES experiments(id) ON DELETE CASCADE
);

CREATE TABLE runs (
    id              TEXT    PRIMARY KEY,
    experiment_id   INTEGER NOT NULL,
    name            TEXT,
    status          TEXT    NOT NULL DEFAULT 'RUNNING',
    start_time      INTEGER NOT NULL,
    end_time        INTEGER,
    artifact_uri    TEXT    NOT NULL,
    lifecycle_stage TEXT    NOT NULL DEFAULT 'active',
    user_id         TEXT,
    source_type     TEXT,
    source_name     TEXT,
    run_kind        TEXT    NOT NULL DEFAULT 'classic', parent_run_id TEXT REFERENCES runs(id) ON DELETE SET NULL,
    FOREIGN KEY (experiment_id) REFERENCES experiments(id) ON DELETE CASCADE,
    CHECK (status IN ('RUNNING','SCHEDULED','FINISHED','FAILED','KILLED')),
    CHECK (lifecycle_stage IN ('active','deleted')),
    CHECK (run_kind IN ('classic','trace','eval'))
);

CREATE TABLE metrics (
    run_id    TEXT    NOT NULL,
    key       TEXT    NOT NULL,
    value     REAL    NOT NULL,
    timestamp INTEGER NOT NULL,
    step      INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (run_id, key, timestamp, step),
    FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE
);

CREATE TABLE params (
    run_id TEXT NOT NULL,
    key    TEXT NOT NULL,
    value  TEXT NOT NULL,
    PRIMARY KEY (run_id, key),
    FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE
);

CREATE TABLE tags (
    run_id TEXT NOT NULL,
    key    TEXT NOT NULL,
    value  TEXT NOT NULL,
    PRIMARY KEY (run_id, key),
    FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE
);

CREATE TABLE traces (
    id              TEXT PRIMARY KEY,
    trace_id        TEXT NOT NULL,
    parent_id       TEXT,
    run_id          TEXT,
    name            TEXT NOT NULL,
    span_kind       TEXT,
    start_time      INTEGER NOT NULL,
    end_time        INTEGER,
    attributes_json TEXT,
    events_json     TEXT,
    status_code     TEXT,
    status_message  TEXT,
    FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE,
    FOREIGN KEY (parent_id) REFERENCES traces(id) ON DELETE CASCADE
);

CREATE TABLE evals (
    run_id          TEXT PRIMARY KEY,
    target_run_ids  TEXT NOT NULL,
    dataset_ref     TEXT,
    score           REAL,
    metrics_json    TEXT,
    FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE
);

CREATE TABLE sessions (
    id          TEXT    PRIMARY KEY,          -- 32-byte hex, opaque random token
    user_id     TEXT    NOT NULL,             -- email or OIDC "sub" claim
    user_email  TEXT,
    user_name   TEXT,
    auth_method TEXT    NOT NULL,             -- 'basic' | 'oidc'
    created_at  INTEGER NOT NULL,             -- unix ms
    expires_at  INTEGER NOT NULL,             -- unix ms
    last_seen   INTEGER NOT NULL              -- unix ms
);

CREATE TABLE workspaces (
    id               TEXT    PRIMARY KEY,
    name             TEXT    NOT NULL,
    description      TEXT,
    creation_time    INTEGER NOT NULL,
    last_update_time INTEGER NOT NULL
);

CREATE TABLE "experiments" (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    name              TEXT    NOT NULL,
    artifact_location TEXT    NOT NULL,
    lifecycle_stage   TEXT    NOT NULL DEFAULT 'active',
    creation_time     INTEGER NOT NULL,
    last_update_time  INTEGER NOT NULL,
    workspace_id      TEXT    NOT NULL DEFAULT 'default'
        REFERENCES workspaces(id) ON DELETE CASCADE,
    CHECK (lifecycle_stage IN ('active','deleted')),
    UNIQUE (workspace_id, name)
);

CREATE TABLE workspace_members (
    workspace_id TEXT NOT NULL,
    user_id      TEXT NOT NULL,
    role         TEXT NOT NULL DEFAULT 'editor',
    PRIMARY KEY (workspace_id, user_id),
    FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CHECK (role IN ('viewer','editor','admin'))
);

CREATE TABLE workspace_tags (
    workspace_id TEXT NOT NULL,
    key          TEXT NOT NULL,
    value        TEXT NOT NULL,
    PRIMARY KEY (workspace_id, key),
    FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
);

CREATE TABLE datasets (
    name        TEXT NOT NULL,
    digest      TEXT NOT NULL,
    source_type TEXT,
    source      TEXT,
    schema      TEXT,
    profile     TEXT,
    PRIMARY KEY (name, digest)
);

CREATE TABLE dataset_inputs (
    id        INTEGER PRIMARY KEY AUTOINCREMENT,
    run_id    TEXT NOT NULL,
    name      TEXT NOT NULL,
    digest    TEXT NOT NULL,
    FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE,
    FOREIGN KEY (name, digest) REFERENCES datasets(name, digest)
);

CREATE TABLE dataset_input_tags (
    dataset_input_id INTEGER NOT NULL,
    key   TEXT NOT NULL,
    value TEXT NOT NULL,
    PRIMARY KEY (dataset_input_id, key),
    FOREIGN KEY (dataset_input_id) REFERENCES dataset_inputs(id) ON DELETE CASCADE
);

CREATE TABLE run_notes (
    run_id      TEXT NOT NULL,
    content     TEXT NOT NULL,
    updated_at  INTEGER NOT NULL,
    updated_by  TEXT,
    PRIMARY KEY (run_id),
    FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE
);

CREATE TABLE webhooks (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    name          TEXT    NOT NULL,
    url           TEXT    NOT NULL,
    events        TEXT    NOT NULL,    -- comma-separated: run_finished,run_failed,run_started
    experiment_id INTEGER,              -- nullable; NULL = all experiments in workspace
    workspace_id  TEXT    NOT NULL DEFAULT 'default',
    secret        TEXT,                 -- HMAC-SHA256 signing key
    created_at    INTEGER NOT NULL,
    last_status   INTEGER,              -- HTTP status of last delivery
    last_attempt  INTEGER,              -- unix ms
    enabled       INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE dashboards (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    workspace_id TEXT    NOT NULL DEFAULT 'default',
    project      TEXT    NOT NULL,
    widgets      TEXT    NOT NULL DEFAULT '[]',  -- JSON array of widget configs
    created_at   INTEGER NOT NULL,
    updated_at   INTEGER NOT NULL,
    UNIQUE (workspace_id, project)
);

CREATE TABLE metrics_latest (
    run_id    TEXT    NOT NULL,
    key       TEXT    NOT NULL,
    value     REAL    NOT NULL,
    timestamp INTEGER NOT NULL,
    step      INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (run_id, key),
    FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE
);

CREATE TABLE datasets_v2 (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    name          TEXT NOT NULL,
    version       INTEGER NOT NULL,        -- per-name auto-incrementing 1..N
    content_hash  TEXT NOT NULL,           -- server-verified sha256 hex of bytes
    size_bytes    INTEGER NOT NULL DEFAULT 0,
    schema_json   TEXT,                    -- optional JSON schema / column types
    description   TEXT,
    workspace_id  TEXT NOT NULL DEFAULT 'default',
    created_at    INTEGER NOT NULL,
    created_by    TEXT,
    lifecycle_stage TEXT NOT NULL DEFAULT 'active' CHECK (lifecycle_stage IN ('active','deleted')),
    UNIQUE (workspace_id, name, version)
);

CREATE TABLE dataset_lineage (
    child_id  INTEGER NOT NULL,
    parent_id INTEGER NOT NULL,
    PRIMARY KEY (child_id, parent_id),
    FOREIGN KEY (child_id)  REFERENCES datasets_v2(id) ON DELETE CASCADE,
    FOREIGN KEY (parent_id) REFERENCES datasets_v2(id) ON DELETE CASCADE
);

CREATE TABLE peers (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    name         TEXT    NOT NULL,
    url          TEXT    NOT NULL,
    secret       TEXT    NOT NULL,         -- HMAC secret (hex 64 chars)
    workspace_id TEXT    NOT NULL DEFAULT 'default',
    added_at     INTEGER NOT NULL,
    last_seen    INTEGER,
    status       TEXT    NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending','connected','error')),
    last_error   TEXT,
    UNIQUE (workspace_id, name)
);

CREATE TABLE events (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    ts_ms       INTEGER NOT NULL,             -- unix ms when the mutation happened
    kind        TEXT    NOT NULL,             -- run_update | run_lifecycle | run_parent | tag_set | tag_delete
    entity_type TEXT    NOT NULL,             -- 'run' for v1.5; reserved for 'experiment' etc.
    entity_id   TEXT    NOT NULL,             -- the run.id (or future experiment_id as text)
    payload     TEXT    NOT NULL DEFAULT '{}',-- JSON; shape varies by kind
    CHECK (kind IN ('run_update','run_lifecycle','run_parent','tag_set','tag_delete'))
);

CREATE TABLE dataset_inputs_v2 (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    run_id      TEXT    NOT NULL,
    dataset_id  INTEGER NOT NULL,
    tags_json   TEXT    NOT NULL DEFAULT '[]',
    FOREIGN KEY (run_id)     REFERENCES runs(id)        ON DELETE CASCADE,
    FOREIGN KEY (dataset_id) REFERENCES datasets_v2(id) ON DELETE CASCADE
);

CREATE TABLE "prompts" (
    name         TEXT    NOT NULL,
    version      INTEGER NOT NULL,
    workspace_id TEXT    NOT NULL DEFAULT 'default'
        REFERENCES workspaces(id) ON DELETE CASCADE,
    content      TEXT    NOT NULL,
    content_hash TEXT    NOT NULL,
    created_at   INTEGER NOT NULL,
    created_by   TEXT,
    description  TEXT,
    PRIMARY KEY (workspace_id, name, version)
);

CREATE TABLE "prompt_aliases" (
    workspace_id TEXT    NOT NULL DEFAULT 'default',
    name         TEXT    NOT NULL,
    alias        TEXT    NOT NULL,
    version      INTEGER NOT NULL,
    PRIMARY KEY (workspace_id, name, alias),
    FOREIGN KEY (workspace_id, name, version) REFERENCES "prompts"(workspace_id, name, version) ON DELETE CASCADE
);

CREATE TABLE "registered_models" (
    name             TEXT    NOT NULL,
    workspace_id     TEXT    NOT NULL DEFAULT 'default'
        REFERENCES workspaces(id) ON DELETE CASCADE,
    description      TEXT,
    creation_time    INTEGER NOT NULL,
    last_update_time INTEGER NOT NULL,
    PRIMARY KEY (workspace_id, name)
);

CREATE TABLE "model_versions" (
    name              TEXT    NOT NULL,
    version           INTEGER NOT NULL,
    workspace_id      TEXT    NOT NULL DEFAULT 'default',
    description       TEXT,
    user_id           TEXT,
    current_stage     TEXT    NOT NULL DEFAULT 'None',
    source            TEXT    NOT NULL,
    run_id            TEXT,
    status            TEXT    NOT NULL DEFAULT 'READY',
    status_message    TEXT,
    creation_time     INTEGER NOT NULL,
    last_update_time  INTEGER NOT NULL,
    PRIMARY KEY (workspace_id, name, version),
    FOREIGN KEY (workspace_id, name) REFERENCES "registered_models"(workspace_id, name) ON DELETE CASCADE,
    CHECK (current_stage IN ('None','Staging','Production','Archived')),
    CHECK (status IN ('READY','PENDING','FAILED'))
);

CREATE TABLE "registered_model_tags" (
    name         TEXT NOT NULL,
    workspace_id TEXT NOT NULL DEFAULT 'default',
    key          TEXT NOT NULL,
    value        TEXT NOT NULL,
    PRIMARY KEY (workspace_id, name, key),
    FOREIGN KEY (workspace_id, name) REFERENCES "registered_models"(workspace_id, name) ON DELETE CASCADE
);

CREATE TABLE "model_version_tags" (
    name         TEXT NOT NULL,
    version      INTEGER NOT NULL,
    workspace_id TEXT NOT NULL DEFAULT 'default',
    key          TEXT NOT NULL,
    value        TEXT NOT NULL,
    PRIMARY KEY (workspace_id, name, version, key),
    FOREIGN KEY (workspace_id, name, version) REFERENCES "model_versions"(workspace_id, name, version) ON DELETE CASCADE
);

CREATE TABLE "model_aliases" (
    name         TEXT NOT NULL,
    workspace_id TEXT NOT NULL DEFAULT 'default',
    alias        TEXT NOT NULL,
    version      INTEGER NOT NULL,
    PRIMARY KEY (workspace_id, name, alias),
    FOREIGN KEY (workspace_id, name, version) REFERENCES "model_versions"(workspace_id, name, version) ON DELETE CASCADE
);

CREATE INDEX idx_runs_experiment_status ON runs(experiment_id, status, start_time DESC);

CREATE INDEX idx_runs_lifecycle ON runs(lifecycle_stage);

CREATE INDEX idx_metrics_run_key ON metrics(run_id, key, step);

CREATE INDEX idx_traces_run ON traces(run_id);

CREATE INDEX idx_traces_parent ON traces(parent_id);

CREATE INDEX idx_traces_trace ON traces(trace_id);

CREATE INDEX idx_sessions_expires ON sessions(expires_at);

CREATE INDEX idx_experiments_workspace ON experiments(workspace_id, lifecycle_stage);

CREATE INDEX idx_dataset_inputs_run ON dataset_inputs(run_id);

CREATE INDEX idx_runs_parent ON runs(parent_run_id);

CREATE INDEX idx_webhooks_workspace ON webhooks(workspace_id, enabled);

CREATE INDEX idx_dashboards_workspace ON dashboards(workspace_id);

CREATE INDEX idx_metrics_latest_key_value ON metrics_latest(key, value DESC, run_id);

CREATE INDEX idx_datasets_v2_hash ON datasets_v2(content_hash);

CREATE INDEX idx_datasets_v2_workspace_name ON datasets_v2(workspace_id, name, version DESC);

CREATE INDEX idx_dataset_lineage_parent ON dataset_lineage(parent_id);

CREATE INDEX idx_peers_workspace ON peers(workspace_id, status);

CREATE INDEX idx_events_entity_ts
    ON events(entity_type, entity_id, ts_ms, id);

CREATE INDEX idx_events_ts ON events(ts_ms);

CREATE INDEX idx_dataset_inputs_v2_run ON dataset_inputs_v2(run_id);

CREATE INDEX idx_prompts_hash ON prompts(workspace_id, name, content_hash);

CREATE INDEX idx_mv_run ON model_versions(run_id);

CREATE INDEX idx_mv_stage ON model_versions(current_stage);

CREATE TRIGGER trg_metrics_latest_ai
AFTER INSERT ON metrics
BEGIN
    INSERT INTO metrics_latest (run_id, key, value, timestamp, step)
    VALUES (NEW.run_id, NEW.key, NEW.value, NEW.timestamp, NEW.step)
    ON CONFLICT(run_id, key) DO UPDATE SET
        value     = NEW.value,
        timestamp = NEW.timestamp,
        step      = NEW.step
        WHERE NEW.timestamp > metrics_latest.timestamp
           OR (NEW.timestamp = metrics_latest.timestamp AND NEW.step >= metrics_latest.step);
END;

CREATE TRIGGER trg_metrics_latest_ad
AFTER DELETE ON metrics
WHEN EXISTS (
    SELECT 1 FROM metrics_latest
    WHERE run_id = OLD.run_id AND key = OLD.key
      AND timestamp = OLD.timestamp AND step = OLD.step
)
BEGIN
    DELETE FROM metrics_latest WHERE run_id = OLD.run_id AND key = OLD.key;
    INSERT INTO metrics_latest (run_id, key, value, timestamp, step)
    SELECT m.run_id, m.key, m.value, m.timestamp, m.step
    FROM metrics m
    WHERE m.run_id = OLD.run_id AND m.key = OLD.key
    ORDER BY m.timestamp DESC, m.step DESC
    LIMIT 1;
END;

