// Generates internal/migrations/baseline/v2_baseline.sql by applying all
// migrations to a fresh in-memory SQLite database and dumping the
// resulting schema in dependency-safe order.
//
// Run from repo root:
//
//	go run ./scripts/gen-baseline-schema > internal/migrations/baseline/v2_baseline.sql
//
// The generated file is checked in. TestSquashEquivalence in
// internal/migrations/embed_test.go verifies that the baseline produces
// the same schema as applying 001..NN sequentially — any drift fails CI.
package main

import (
	"context"
	"database/sql"
	"fmt"
	"os"
	"sort"
	"strings"

	_ "modernc.org/sqlite"

	"github.com/gorevds/litemlflow/internal/migrations"
)

func main() {
	ctx := context.Background()
	db, err := sql.Open("sqlite", ":memory:")
	if err != nil {
		fatal(err)
	}
	defer db.Close()

	// Apply all migrations.
	if err := migrations.Apply(ctx, db); err != nil {
		fatal(fmt.Errorf("apply migrations: %w", err))
	}

	// Dump in dependency-safe order: tables first (by FK depth), then
	// indexes, then triggers. SQLite's sqlite_schema has rowids ordered
	// by creation time, which matches the migration sequence — so we
	// can simply select with ORDER BY rowid for the migration-equivalent
	// schema.
	type schemaItem struct {
		Kind, Name, TblName, SQL string
	}
	var items []schemaItem
	rows, err := db.QueryContext(ctx, `
		SELECT type, name, tbl_name, sql
		FROM sqlite_schema
		WHERE sql IS NOT NULL
		  AND name NOT LIKE 'sqlite_%'
		  AND name NOT LIKE '__lmf_%'
		ORDER BY rowid
	`)
	if err != nil {
		fatal(err)
	}
	defer rows.Close()
	for rows.Next() {
		var it schemaItem
		if err := rows.Scan(&it.Kind, &it.Name, &it.TblName, &it.SQL); err != nil {
			fatal(err)
		}
		items = append(items, it)
	}
	if err := rows.Err(); err != nil {
		fatal(err)
	}

	// Stable secondary sort: tables → indexes → triggers within each
	// group, preserving creation order within group.
	sort.SliceStable(items, func(i, j int) bool {
		return kindRank(items[i].Kind) < kindRank(items[j].Kind)
	})

	var buf strings.Builder
	buf.WriteString("-- v2_baseline.sql — consolidated schema for fresh v2.1+ installs.\n")
	buf.WriteString("--\n")
	buf.WriteString("-- AUTOGENERATED by scripts/gen-baseline-schema. Do not hand-edit.\n")
	buf.WriteString("-- Regenerate: go run ./scripts/gen-baseline-schema > internal/migrations/baseline/v2_baseline.sql\n")
	buf.WriteString("--\n")
	buf.WriteString("-- This file is NOT applied by the runner today; it's the canonical\n")
	buf.WriteString("-- target for the v3.0 migration squash. TestSquashEquivalence in\n")
	buf.WriteString("-- internal/migrations/embed_test.go enforces that applying it produces\n")
	buf.WriteString("-- the same schema as applying 001..NN sequentially.\n")
	buf.WriteString("--\n")
	buf.WriteString("-- v2.1 T4.18 (partial): baseline materialized, runner switch deferred to v3.0.\n\n")

	for _, it := range items {
		buf.WriteString(it.SQL)
		buf.WriteString(";\n\n")
	}

	os.Stdout.WriteString(buf.String())
}

func kindRank(k string) int {
	switch k {
	case "table":
		return 0
	case "index":
		return 1
	case "trigger":
		return 2
	case "view":
		return 3
	}
	return 9
}

func fatal(err error) {
	fmt.Fprintf(os.Stderr, "error: %v\n", err)
	os.Exit(1)
}
